services:
  nginx:
    container_name: nginx
    hostname: nginx
    build: ./nginx
    # volumes:
    #   - ./var/log/nginx:/var/log/nginx #log файлы.
      # - ./volumes/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro #Конфигурация nginx.
      # - ./volumes/etc/nginx/ssl:/etc/nginx/ssl:ro #сертификаты
      # - /var/www/DOMAIN_NAME:/var/www/DOMAIN_NAME #Домашняя директория
    ports:
      - "8080:80"
      - "8081:443"
    restart:
      always
    networks:
      - get5

  redis:
    image: redis:6
    command: redis-server --requirepass Z3fZeK9W6jBfMJY
    container_name: redis
    networks:
      - get5
    restart: always

  get5db:
    image: yobasystems/alpine-mariadb
    container_name: get5db
    restart: always
    networks:
      - get5
    environment:
      - MYSQL_ROOT_PASSWORD=FJqXv2dd3TeFAn3
      - MYSQL_DATABASE=get5
      - MYSQL_USER=get5
      - MYSQL_PASSWORD=FJqXv2dd3TeFAn3
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_general_ci
    ports:
      - 3306:3306

  g5api:
    image: ghcr.io/phlexplexico/g5api:latest
    depends_on:
      - get5db
    container_name: G5API
    networks:
      - get5
    volumes:
      - ./public:/Get5API/public
    environment:
      - NODE_ENV=production
      - PORT=3301
      - DBKEY=0fc9c89ce985fa8066398b1be5c730f7 #CHANGME https://www.random.org/cgi-bin/randbyte?nbytes=16&format=h
      - STEAMAPIKEY=1560BA93C86CE50229DF536680D4AE26
      - HOSTNAME=https://seriousvitamin.ru
      - SHAREDSECRET=Z3TLmUEVpvXdE5H7UdnEbNSySak9gj
      - CLIENTHOME=https://seriousvitamin.ru
      - APIURL=https://seriousvitamin.ru/api
      - SQLUSER=get5
      - SQLPASSWORD=FJqXv2dd3TeFAn3
      - SQLPORT=3306
      - DATABASE=get5
      - SQLHOST=get5db
      - ADMINS=76561198024887034
      - SUPERADMINS=76561198024887034
      - REDISURL=redis://:Z3fZeK9W6jBfMJY@redis:6379
      - REDISTTL=86400
      - USEREDIS=true
      - UPLOADDEMOS=true
      - LOCALLOGINS=false
    restart: always
    ports:
      - 3301:3301

  g5v:
    image: ghcr.io/phlexplexico/g5v:latest
    container_name: G5V-Front-End
    networks:
      - get5
    restart: always
    ports:
      - 7000:80
networks:
  get5:
    external: true